version: '3.6'

services:
  app:
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/estadisticas
    ports:
     - "2409:2409"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data: