version: '3.7'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  
  api:
    image: $DOCKERHUB_USERNAME/reportes_api:latest
    build: .
    environment:
      - MONGO_URI=mongodb://mongodb:27017/estadisticas
    ports:
     - "2409:2409"
    depends_on:
      - mongodb

