# This is a basic workflow to help you get started with Actions

name: Docker Image CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


build:

    runs-on: ubuntu-latest

    steps:
    - name: Hace checkout del repositorio
      uses: actions/checkout@v3
      
    - name: Login en Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Configura Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Crear y subir imagen
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/sql-server:latest
        
    - name: digest de la imagen
      run: echo ${{ steps.docker_build.outputs.digest }}
